project:
  type: website
  render:
    - "*.qmd"
  post-render: quarto/scripts/restoreMarkdownToHeirarchy.sh
  #resources:

website:
  title: "Effective Python: Notes"
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - Chapter_01/Chapter_01.qmd
format:
  html:
    code-fold: false
    code-links: repo
  gfm:
    filters:
      - quarto/scripts/strip_ansi.lua
toc: true
toc-depth: 6
format-links: false
execute:
  enabled: true
  error: true
engine: jupyter
