project:
  type: website
  render:
    - "*.qmd"
  post-render: quarto/scripts/restoreMarkdownToHeirarchy.sh
  #resources:

website:
  title: "Effective Python: Notes"
  page-navigation: true
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Chapter_01/Chapter_01.qmd
        contents:
          - Chapter_01/Item_001/Item_001.qmd
          - Chapter_01/Item_002/Item_002.qmd
          - Chapter_01/Item_003/Item_003.qmd
          - Chapter_01/item_004/Item_004.qmd
          - Chapter_01/item_005/Item_005.qmd
format:
  html:
    code-fold: false
    code-links: repo
  gfm:
    filters:
      - quarto/scripts/strip_ansi.lua
  ipynb: default
toc: true
toc-depth: 6
format-links: false
execute:
  enabled: true
  error: true
engine: jupyter
