---
title: "Item 115: Use `tracemalloc` to Understand Memory Usage and Leaks"
---

## Notes

- By default Python is a memory-managed language
- CPython uses a reference counting garbage collector
    - Once all references to an object expire, it is queued for cleanup
    - Also uses a cycle-detector to clean-up self-referential objects
- Usually you can avoid worrying about allocating or deallocating memory
    - In practice programs might run out of memory from references overstaying their welcome
- It can be hard to work out how or where a python program is consuming memory

- Can use the `gc` built-in module
    - Let's us see all memory known to the garbage collector
    - Unfortunately this is quite blunt

```{python}
import gc
import os

# Before module
found_objects = gc.get_objects()
print("Before:", len(found_objects))


class MyObject:
    def __init__(self):
        self.data = os.urandom(100)


def get_data():
    values = []
    for _ in range(100):
        obj = MyObject()
        values.append(obj)
    return values


def run():
    deep_values = []
    for _ in range(100):
        deep_values.append(get_data())
    return deep_values


waste_memory = run()
found_objects = gc.get_objects()
print("After:   ", len(found_objects))
for obj in found_objects[:3]:
    print(repr(obj)[:100])
```

- Lot's of the memory above is from running the jupyter notebook
- But `gc.get_objects` doesn't provide context about the object's it's found
    - Such as how they were created
- Typically it is better to understand *where* an object came from rather than *what* it is
- Python 3.4 introduces the `tracemalloc` built-in library
    - Allows you to link an object to where it was allocated

```{python}
import os
import tracemalloc

# Before module
tracemalloc.start(10)  # Set stack depth
time1 = tracemalloc.take_snapshot()  # Before MyObject


class MyObject:
    def __init__(self):
        self.data = os.urandom(100)


def get_data():
    values = []
    for _ in range(100):
        obj = MyObject()
        values.append(obj)
    return values


def run():
    deep_values = []
    for _ in range(100):
        deep_values.append(get_data())
    return deep_values


waste_memory = run()
time2 = tracemalloc.take_snapshot()  # After snapshot

stats = time2.compare_to(time1, "lineno")  # Compare snapshots
for stat in stats[:3]:
    print(stat)
```

- `size` and `count` labels help identify which objects dominate memory usage
    - Also links where they are allocated
- Can print the full stack trace

```{python}
import tracemalloc

tracemalloc.start(10)
time1 = tracemalloc.take_snapshot()


class MyObject:
    def __init__(self):
        self.data = os.urandom(1000)


def get_data():
    values = []
    for _ in range(100):
        obj = MyObject()
        values.append(obj)
    return values


def run():
    deep_values = []
    for _ in range(100):
        deep_values.append(get_data())
    return deep_values


waste_memory = run()
time2 = tracemalloc.take_snapshot()  # After snapshot

stats = time2.compare_to(time1, "traceback")
top = stats[0]
print("Biggest offender is:")
print("\n".join(top.traceback.format()))
```

- Stack trace is the best mechanism for differentiating different usages of the same function or class
    - Can work out which usages are causing memory issues
- For more advanced memory profiling consider community packages (See [Item 116](../../Chapter_14/Item_116/item_116.qmd))
    - e.g. [`Memray`](https://github.com/bloomberg/memray)

## Things to Remember

- It can be difficult to understand memory consumption in Python
- The `gc` module can be used to understand what objects exist
    - Does not provide context of how they were allocated
- `tracemalloc` built-in provides tools for understanding memory consumption and allocation
